services:
  webapp:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://test:test123@mongodb:27017/webapp?authSource=admin
      - PORT=3000
    depends_on:
      - mongodb
    restart: unless-stopped
    volumes:
      - ./course-data:/usr/src/app/course-data

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
    - MONGO_INITDB_ROOT_USERNAME=test
    - MONGO_INITDB_ROOT_PASSWORD=test123
    restart: unless-stopped

volumes:
  mongodb_data: 